name: AsmlaurGhost
main: me.JCW313.AsmalurGhost.AsmalurGhost
version: 0.0.5
description: >
             Hide new players.
Permissions:
  access.ghost:
    description: Hides new players!
    default: false
